sudo: false
language: python

install:
  - pip install tox

script:
  - tox -e $py

notifications:
  irc:
    channels:
      - "chat.freenode.net##mypy"
    use_notice: true

matrix:
  include:
    - python: "3.2"
      env: py=py32
    - python: "3.3"
      env: py=py33
    - python: "3.4"
      env: py=py34
    - python: "3.5"
      env: py=py35
    - python: "pypy3"
      env: py=pypy3
