sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  # Pypy build is disabled because it doubles the travis build time, and it rarely fails
  # unless one one of the other builds fails.
  # - "pypy3"

install:
  - pip install -r requirements-testing.txt
  - python setup.py install

script:
  - python runtests.py -v
