if: tag IS present OR type = pull_request OR (branch = master AND type = push)   # we only CI the master, tags and PRs

language: python
# cache package wheels (1 cache per python version)
cache: pip
dist: xenial
sudo: required

env:
  TOXENV=py
  EXTRA_ARGS=-n 12

jobs:
  include:
  - python: 3.4
    dist: trusty
  # Specifically request 3.5.1 because we need to be compatible with that.
  - python: 3.5.1
    dist: trusty
  - python: 3.6    # 3.6.3  pip  9.0.1
  - python: 3.7    # 3.7.0  pip 10.0.1
  - python: 3.8-dev
  - python: 3.7
    env:
    - TOXENV=type
    - EXTRA_ARGS=
  - python: 3.7
    env:
    - TOXENV=lint
    - EXTRA_ARGS=

install:
- pip install -U tox
- tox --notest

script:
- tox -- $EXTRA_ARGS
