sudo: false
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  # Pypy build is disaabled because it doubles the travis build time, and it rarely fails
  # unless one one of the other builds fails.
  # - "pypy3"

install:
  - pip install -r test-requirements.txt

script:
  - python setup.py install
  - mkdir elsewhere
  - cd elsewhere
  - mkdir tmp-test-dirs
  - ln -s ../runtests.py
  - python runtests.py -v

notifications:
  irc:
    channels:
      - "chat.freenode.net##mypy"
    use_notice: true
