cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      EXTRA_ARGS:
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"
      EXTRA_ARGS: "mypyc/test/test_run.py mypyc/test/test_external.py"

install:
    - "git submodule update --init mypy/typeshed"
    - "%PYTHON%\\python.exe -m pip install -U setuptools tox==3.9.0"
    - "%PYTHON%\\python.exe -m tox -e py37 --notest"

build: off

test_script:
    - "%PYTHON%\\python.exe -m tox -e py37 %EXTRA_ARGS%"
    - "IF ($env:APPVEYOR_REPO_TAG -eq $False) { pip install -r mypy-requirements.txt; CC=clang MYPYC_OPT_LEVEL=0 python3 setup.py --use-mypyc build_ext --inplace }"

skip_commits:
  files:
    - docs/**/*
    - '**/*.rst'
    - '**/*.md'
    - .gitignore
    - .travis.yml
    - CREDITS
    - LICENSE

skip_branch_with_pr: true
