[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    # Officially supported pybind11 version. This is pinned to guarantee 100% reproducible CI.
    # As a results, needs to be updated deliberately at will.
    "pybind11==2.9.2",
]

build-backend = "setuptools.build_meta"