contact_links:
  - about: "You can find information on the mypy website."
    name: "Mypy website"
    url: "http://www.mypy-lang.org/"
  - about: "Please check the docs before filing new issues."
    name: "Common issues and solutions"
    url: "https://mypy.readthedocs.io/en/stable/common_issues.html"
  - about: "Please ask and answer usage questions on the mypy Gitter."
    name: "Questions or Chat"
    url: "https://gitter.im/python/typing"
