name: main

on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**/*.rst'
    - '**/*.md'
    - .gitignore
    - .travis.yml
    - CREDITS
    - LICENSE

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [windows-py37-32, windows-py37-64,
               ubuntu-py37-64, ubuntu-py38-64]
        include:
        - name: windows-py37-32
          python: '3.7'
          arch: x86
          os: windows-latest
          toxenv: py37
        - name: windows-py37-64
          python: '3.7'
          arch: x64
          os: windows-latest
          toxenv: py37
        - name: ubuntu-py37-64
          python: '3.7'
          arch: x64
          os: ubuntu-latest
          toxenv: py
        - name: ubuntu-py38-64
          python: '3.8'
          arch: x64
          os: ubuntu-latest
          toxenv: py

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}
    - name: install tox
      run: pip install --upgrade 'setuptools!=50' 'virtualenv<16.7.11' tox==3.20.1
    - name: setup tox environment
      run: tox -e ${{ matrix.toxenv }} --notest
    - name: test
      env:
        EXTRA_ARGS: "-n 2"
      run: tox -e ${{ matrix.toxenv }} --skip-pkg-install -- $EXTRA_ARGS
