name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main, master, 'release*']
    tags: ['*']
  pull_request:
    paths-ignore:
    - 'docs/**'
    - 'mypyc/doc/**'
    - '**/*.rst'
    - '**/*.md'
    - .gitignore
    - CREDITS
    - LICENSE

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  python-nightly:
    runs-on: ubuntu-latest
    name: Test suite with Python nightly
    steps:
      # - uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      # TODO try - uses: deadsnakes/action@v3.2.0
      #   with:
      #     python-version: '3.13-dev'

      # Build Python from 3.13 branch
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            gdb \
            lcov \
            libbz2-dev \
            libffi-dev \
            libgdbm-dev \
            liblzma-dev \
            libncurses5-dev \
            libreadline6-dev \
            libsqlite3-dev \
            libssl-dev \
            lzma \
            lzma-dev \
            tk-dev \
            uuid-dev \
            zlib1g-dev
      - name: Compile Python from 3.13 branch
        run: |
          git clone --depth 1 --branch 3.13
          cd cpython
          ./configure
          make -j 0
          make install
      - name: Install tox
        run: python3.13 -m pip install setuptools==68.2.2 tox==4.11.0
      - name: Setup tox environment
        run: python3.13 -m tox run -e py --notest
      - name: Test
        run: python3.13 -m tox run -e py --skip-pkg-install -- "-n 4"
        continue-on-error: true
      - name: Mark as a success
        run: exit 0

  python_32bits:
    runs-on: ubuntu-latest
    name: Test mypyc suite with 32-bit Python
    env:
      TOX_SKIP_MISSING_INTERPRETERS: False
      # Rich (pip)
      FORCE_COLOR: 1
      # Tox
      PY_COLORS: 1
      # Mypy (see https://github.com/python/mypy/issues/7771)
      TERM: xterm-color
      MYPY_FORCE_COLOR: 1
      MYPY_FORCE_TERMINAL_WIDTH: 200
      # Pytest
      PYTEST_ADDOPTS: --color=yes
      CXX: i686-linux-gnu-g++
      CC: i686-linux-gnu-gcc
    steps:
      - uses: actions/checkout@v4
      - name: Install 32-bit build dependencies
        run: |
          sudo dpkg --add-architecture i386 && \
          sudo apt-get update && sudo apt-get install -y \
            zlib1g-dev:i386 \
            libgcc-s1:i386 \
            g++-i686-linux-gnu \
            gcc-i686-linux-gnu \
            libffi-dev:i386 \
            libssl-dev:i386 \
            libbz2-dev:i386 \
            libncurses-dev:i386 \
            libreadline-dev:i386 \
            libsqlite3-dev:i386 \
            liblzma-dev:i386 \
            uuid-dev:i386
      - name: Compile, install, and activate 32-bit Python
        uses: gabrielfalcao/pyenv-action@v13
        with:
          default: 3.11.1
          command: python -c "import platform; print(f'{platform.architecture()=} {platform.machine()=}');"
      - name: Install tox
        run: pip install setuptools==68.2.2 tox==4.11.0
      - name: Setup tox environment
        run: tox run -e py --notest
      - name: Test
        run: tox run -e py --skip-pkg-install -- -n 4 mypyc/test/
